services:
  payload:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - '127.0.0.1:3000:3000'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    volumes:
      - ../media:/app/media
    env_file:
      - .env
    restart: always